### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by Eutopiax** [RayZhhh/funsearch#1]
Hello author.Thank you for your greate work.When i use the repository code,i meet the problem that the result quickly rise from -500 to -212.Do you meet the same problem in your implementation?

**Comment by RayZhhh** [comment]
Hello! Thank you for your report! I think it's not a bug😂, this behavior is entirely normal. On this test dataset, it's common to get a score value of -212.75. If your 'priority' function returns an array of all zeros, it would also result in this value. This rapid increase is due to the simplicity of the problem, causing the score to rise quickly.

**Comment by Eutopiax** [comment]
ok.Thanks you a lot!
